// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/counter.tsx";
import * as $3 from "./routes/create.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Input.tsx";
import * as $$3 from "./islands/Label.tsx";
import * as $$4 from "./islands/Link.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/counter.tsx": $2,
    "./routes/create.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Input.tsx": $$2,
    "./islands/Label.tsx": $$3,
    "./islands/Link.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
